import type { Preset } from '@/types/pattern';

const now = Date.now();

/** 기본 내장 프리셋 */
export const defaultPresets: Preset[] = [
  {
    id: 'preset-classic-cotton',
    name: '클래식 면직물',
    params: {
      type: 'plainWeave',
      warpColor: [0.95, 0.93, 0.9],
      weftColor: [0.92, 0.88, 0.82],
      density: 24,
      yarnThickness: 0.65,
      twistAngle: 0,
      flattening: 0.35,
      edgeDefinition: 0.5,
      yarnLoft: 0.55,
      twillDirection: 1,
      satinShift: 2,
      repeatSize: 2,
    },
    pbrSettings: {
      normalStrength: 1.55,
      aoRadius: 2.8,
      aoIntensity: 0.56,
      roughnessBase: 0.75,
      roughnessVariation: 0.17,
      roughnessCavityInfluence: 0.24,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'preset-denim',
    name: '데님',
    params: {
      type: 'twillWeave',
      warpColor: [0.05, 0.08, 0.2],
      weftColor: [0.9, 0.88, 0.85],
      density: 28,
      yarnThickness: 0.75,
      twistAngle: 14,
      flattening: 0.45,
      edgeDefinition: 0.66,
      yarnLoft: 0.7,
      twillDirection: 1,
      satinShift: 2,
      repeatSize: 4,
    },
    pbrSettings: {
      normalStrength: 1.75,
      aoRadius: 3.1,
      aoIntensity: 0.64,
      roughnessBase: 0.8,
      roughnessVariation: 0.22,
      roughnessCavityInfluence: 0.28,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'preset-silk-satin',
    name: '실크 새틴',
    params: {
      type: 'satinWeave',
      warpColor: [0.95, 0.92, 0.85],
      weftColor: [0.88, 0.85, 0.78],
      density: 35,
      yarnThickness: 0.55,
      twistAngle: 0,
      flattening: 0.55,
      edgeDefinition: 0.4,
      yarnLoft: 0.58,
      twillDirection: 1,
      satinShift: 2,
      repeatSize: 5,
    },
    pbrSettings: {
      normalStrength: 1.05,
      aoRadius: 2.5,
      aoIntensity: 0.38,
      roughnessBase: 0.35,
      roughnessVariation: 0.08,
      roughnessCavityInfluence: 0.14,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'preset-carbon-3k-twill',
    name: '카본 3K 능직',
    params: {
      type: 'carbonTwill',
      fiberColor: [0.05, 0.05, 0.05],
      resinColor: [0.08, 0.08, 0.08],
      density: 24,
      yarnThickness: 0.8,
      flattening: 0.6,
      edgeDefinition: 0.84,
      yarnLoft: 0.78,
      towK: 3,
      glossiness: 0.9,
      gapWidth: 0.04,
      weavePattern: 'twill',
    },
    pbrSettings: {
      normalStrength: 1.55,
      aoRadius: 2.2,
      aoIntensity: 0.52,
      roughnessBase: 0.25,
      roughnessVariation: 0.12,
      roughnessCavityInfluence: 0.18,
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'preset-carbon-1k-plain',
    name: '카본 1K 평직',
    params: {
      type: 'carbonPlain',
      fiberColor: [0.05, 0.05, 0.05],
      resinColor: [0.08, 0.08, 0.08],
      density: 20,
      yarnThickness: 0.75,
      flattening: 0.55,
      edgeDefinition: 0.78,
      yarnLoft: 0.7,
      towK: 1,
      glossiness: 0.85,
      gapWidth: 0.05,
      weavePattern: 'plain',
    },
    pbrSettings: {
      normalStrength: 1.45,
      aoRadius: 2.1,
      aoIntensity: 0.5,
      roughnessBase: 0.3,
      roughnessVariation: 0.11,
      roughnessCavityInfluence: 0.16,
    },
    createdAt: now,
    updatedAt: now,
  },
];
